### ISSUE TITLE
Support for LiveDNS API

### ISSUE THREAD

**Issue by drazzib** [prasmussen/gandi-api#15]
Hi!

Since 2015, Gandi has launched a new _LiveDNS_ service which is based on a new [RESTful HTTP API](http://doc.livedns.gandi.net/). This new platform is production ready since december 2016 and will deprecate existing services in the long term.

New _LiveDNS_ platform has more features plus new gifts planned (automatic zone signing, new records including ALIAS, etc.)

It's REST based, so it should not be too much of a headache to implement

Regards,

**Comment by tjamet** [comment]
Hey @drazzib I am also interested in this feature, thanks for finding the documentation
I started working on this integration here: https://github.com/tjamet/gandi-api/tree/live_dns
Hope to be able to go on some time soon :)

**Comment by tjamet** [comment]
I think you can now have a look, the only feature missing seems to be the snapshots, feel free to try it and let me know how it goes for you before I do a PR

**Comment by drazzib** [comment]
Hi @tjamet

Thanks for you work !
I'm using your changes through [StackExchange/dnscontrol](https:/github.com/StackExchange/dnscontrol) project since some months now and its works perfectly.

Regards,

**Comment by tjamet** [comment]
Hi @drazzib my pleasure, nice to know that it works great for you!
Regards,
