### ISSUE TITLE
Add interface to set all records in a zone

### ISSUE THREAD

**Issue by TomOnTime** [prasmussen/gandi-api#4]
`github.com/prasmussen/gandi-api/domain/zone/record` is missing an interface to `domain.zone.record.set`.  It would be useful to be able to simply list a zone_id, version_id, and a list of records and have them sent to this API call as demonstrated in http://doc.rpc.gandi.net/domain/faq.html#replace-the-whole-zone

**Comment by TomOnTime** [comment]
Here is an attempt at adding this kind of functionality. It has been tested in production.  https://github.com/prasmussen/gandi-api/pull/5

**Comment by siilime** [comment]
@TomOnTime It's been merged, can this issue be closed?
