### ISSUE TITLE
Gandi default items_per_page returned by the API is 100

### ISSUE THREAD

**Issue by chewrocca** [prasmussen/gandi-api#7]
I'm not sure if this the right place to ask but Gandi items_per_page when listing domains through their API defaults to 100.  I was wondering if adding the parameter {items_per_page:500} would do the trick, or would something more elegant be desirable?  

The default items_per_page returned by the API is 100 :

Reference: http://doc.rpc.gandi.net/domain/reference.html#DomainListOptions

If you have over 100 domains in your account, then not all will be returned in the default call. You can increase this value or pass the 'page' option to show the second page of results.

Reference: http://doc.rpc.gandi.net/domain/reference.html#domain.list

**Comment by tlimoncelli** [comment]
More important than having >100 domains is having >100 records in a zone.  I just created a DNS zone with 100 records and it works.  If I add 1 more record then it becomes invisible to gandi-api.
